config/routes.rb
Rails.application.routes.draw do

  resources :users

  get 'welcome/index'

  resources :events

  resources :sessions

  get 'upcoming' => 'events#upcoming'
  get 'past' => 'events#past'
  get 'search' => 'events#search'
  get 'myevents' => 'events#myevents'
  get 'authenticate' => 'user_session#authenticate'
  get 'logout' => 'user_session#logout'
  get 'logged' => 'welcome#logged'
  get 'attending' => 'events#myevents_attending'

  get '/signin' => 'user_session#new', :as => :signin
  get '/auth/:provider/callback' => 'user_session#create'

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :sessions
  validates :name, :address, :city, :country, :contact_details, :description, presence: true
  validates :description, length: { maximum: 500 }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authorize, except: [:new, :create, :edit, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.where(status: true)
  end
  
  def upcoming
    @events = Event.where("end_date >= ?", Date.today).order(:start_date)
  end

  def past
    @events = Event.where('end_date < ?', Date.today).order(start_date: :desc)
  end

  def myevents
    if session[:user_id].nil?
      redirect_to root_url, notice: 'Please Log in First'
    else  
      user = User.find(session[:user_id])
      @events = user.events
    end
  end
  # GET /events/1
  # GET /events/1.json
  def show
  end
  
  def search
    if params[:search].blank?
      @events = Event.all
    else
      @events = Event.where("name LIKE ? OR city LIKE ? OR country LIKE ?", 
        params[:search], params[:search],
        params[:search]) 
    end
  end
  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @user = User.find(session[:user_id])
    @event = @user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_url, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :user_id, :start_date, :end_date, :start_time, :end_time, :address, :city, :country, :contact_details, :description, :status, :image_url)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_display.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Address</th>
      <th>City</th>
      <th>Country</th>
      <th>Contact details</th>
      <th>Description</th>
      <th>Status</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @events %>
  </tbody>
</table>

<br>

app/views/events/_event.html.erb
<tr>
  <td><%= link_to "#{ event.name }", event %></td>
  <td><%= event.start_date %></td>
  <td><%= event.end_date %></td>
  <td><%= event.start_time %></td>
  <td><%= event.end_time %></td>
  <td><%= event.address %></td>
  <td><%= event.city %></td>
  <td><%= event.country %></td>
  <td><%= event.contact_details %></td>
  <td><%= event.description %></td>
  <td><%= event.status %></td>
  <td><%= event.image_url %></td>
</tr>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, size: "#{40}" %>
  </div>
  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :start_time %>
    <%= f.time_select :start_time %>
    <%= f.label :end_time %>
    <%= f.time_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class='field'>
    <%= f.label :city %>
    <%= f.text_field :city %>
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :contact_details %><br>
    <%= f.number_field :contact_details %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>Enable
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit 'Save'%>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= link_to 'On Going/Upcoming Events', { controller: 'events', action: 'upcoming' }  %>
<%= link_to 'Past Events', { controller: 'events', action: 'past' } %>
<%= render 'display' %>

app/views/events/myevents.html.erb
<%= link_to 'On Going/Upcoming Events', { controller: 'events', action: 'upcoming' }  %>
<%= link_to 'Past Events', { controller: 'events', action: 'past' } %>
<%= render 'display' %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Cancel', events_path %>

app/views/events/past.html.erb
<%= link_to 'On Going/Upcoming Events', { controller: 'events', action: 'upcoming' }  %>
<%= link_to 'Past Events', { controller: 'events', action: 'past' } %>
<%= render 'display' %>

app/views/events/search.html.erb
<%= link_to 'On Going/Upcoming Events', { controller: 'events', action: 'upcoming' }  %>
<%= link_to 'Past Events', { controller: 'events', action: 'past' } %>
<%= render 'display' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @event.country %>
</p>

<p>
  <strong>Contact details:</strong>
  <%= @event.contact_details %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @event.status %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @event.image_url %>
</p>

<%= link_to 'Show All Sessions' , sessions_path(event_id: @event.id) %>
<% if session[:user_id] == @event.user_id %>
  <%= link_to 'Add New Session', new_session_path(event_id: @event.id) %>
  <%= link_to 'Edit', edit_event_path(@event) %> 
<% end %>  |
<%= link_to 'Back', events_path %>

app/views/events/upcoming.html.erb
<%= link_to 'On Going/Upcoming Events', { controller: 'events', action: 'upcoming' }  %>
<%= link_to 'Past Events', { controller: 'events', action: 'past' } %>
<%= render 'display' %>