config/routes.rb
Rails.application.routes.draw do

  resources :users

  get 'welcome/index'

  resources :events

  resources :sessions

  get 'upcoming' => 'events#upcoming'
  get 'past' => 'events#past'
  get 'search' => 'events#search'
  get 'myevents' => 'events#myevents'
  get 'authenticate' => 'user_session#authenticate'
  get 'logout' => 'user_session#logout'
  get 'logged' => 'welcome#logged'
  get 'attending' => 'events#myevents_attending'

  get '/signin' => 'user_session#new', :as => :signin
  get '/auth/:provider/callback' => 'user_session#create'

  root 'welcome#index'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if session[:user_id].nil? %>
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <% else %>
        <%= link_to 'Home', logged_path, class: 'navbar-brand' %>
      <% end %>    
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'All Events', events_path %></li>
<li><%= link_to 'Events I Created', myevents_path %></li>
<li><%= link_to 'Events I"m Attending', attending_path %></li>
<% if session[:user_id] %>
  <% if session[:admin] %>
    <li><%= link_to 'Users', users_url %></li>
  <% end %> 
  <li id = 'user'>Hello <%= session[:name] %> </li>
  <li> <%= link_to 'Logout', logout_path %></li> 
<% end %>
<li id = 'search'>
  <%= form_tag('search', method: :get) do %>
      <%= text_field_tag :search %>
      <%= submit_tag 'Search' %>
  <% end %>
</li>
<li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>" >
  <header> 
    <%= render 'layouts/navigation' %>
  </header>
  <main role="main">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </main>    
  </div>
</body>
</html>